server:
  port: 20010

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: iotgateway1.com
  client:
    service-url:
      defaultZone: http://ioteureka1.com:20000/eureka,http://ioteureka2.com:20001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true