server:
  port: 20010

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: microservice_test_route
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: iotgateway1.com
  client:
    service-url:
      defaultZone: http://ioteureka1.com:20000/eureka,http://ioteureka2.com:20001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true